#!/bin/bash -e

# Example Input -
#
# stdin = {"cniVersion":"0.3.1","name":"mynet","network":"10.244.0.0/16","subnet":"10.244.0.0/16","type":"bash-cni"}
# $CNI_COMMAND = ADD
# $CNI_CONTAINERID = d6621b6a1b441eb688277913fc0c9b82481e74eef47d08d66f0ba13cdba9cebc
# $CNI_IFNAME = eth0
# $CNI_NETNS = cni-52a7407b-71e5-a807-1f6f-aadb42d7a6b8

DEBUG=1
if [[ ${DEBUG} -gt 0 ]]; then set -x; fi

exec 3>&1 # make stdout available as fd 3 for the result
exec &>> /var/log/bash-cni-plugin.log

IP_STORE=/tmp/reserved_ips # all reserved ips will be stored there

echo "CNI command: $CNI_COMMAND" 

stdin=`cat /dev/stdin`
echo "stdin: $stdin"

allocate_ip(){
	for ip in "${all_ips[@]}"
	do
		reserved=false
		for reserved_ip in "${reserved_ips[@]}"
		do
			if [ "$ip" = "$reserved_ip" ]; then
				reserved=true
				break
			fi
		done
		if [ "$reserved" = false ] ; then
			echo "$ip" >> $IP_STORE
			echo "$ip"
			return
		fi
	done
}

case $CNI_COMMAND in
ADD)
	echo Executing Add
	network=$(echo "$stdin" | jq -r ".network")
	echo Network: $network
	subnet=$(echo "$stdin" | jq -r ".subnet")
	echo Subnet: $subnet
	subnet_mask_size=$(echo $subnet | awk -F  "/" '{print $2}')
	echo Subnet Mask Size: $subnet_mask_size

	all_ips=$(nmap -sL -n $subnet | grep "Nmap scan report" | awk '{print $NF}')
	echo All Ips: $all_ips
	all_ips=(${all_ips[@]})
	echo All Ips Processed: $all_ips
	skip_ip=${all_ips[0]}
	echo Skip Ip: $skip_ip
	gw_ip=${all_ips[1]}
	echo Gateway Ip: $skip_ip
	reserved_ips=$(cat $IP_STORE 2> /dev/null || printf "$skip_ip\n$gw_ip\n") # reserving 10.244.0.0 and 10.244.0.1 
	echo Reserved IPs: $reserved_ips
	reserved_ips=(${reserved_ips[@]})
	echo Reserved IPs Processed: $reserved_ips
	printf '%s\n' "${reserved_ips[@]}" > $IP_STORE
	container_ip=$(allocate_ip)
	echo Container IP: $container_ip

	mkdir -p /var/run/netns/
	echo Running: ln -sfT $CNI_NETNS /var/run/netns/$CNI_CONTAINERID
	ln -sfT $CNI_NETNS /var/run/netns/$CNI_CONTAINERID

	rand=$(tr -dc 'A-F0-9' < /dev/urandom | head -c4)
	host_if_name="veth$rand"
	echo Running: ip link add $CNI_IFNAME type veth peer name $host_if_name
	ip link add h-${host_if_name} type veth peer name c-${host_if_name}

	echo Running: ip link set h-${host_if_name} up
	ip link set h-${host_if_name} up 
	echo Running: ip link set h-${host_if_name} master cni0
	ip link set h-${host_if_name} master cni0 

	echo Running: ip link set c-${host_if_name} netns $CNI_CONTAINERID
	ip link set c-${host_if_name} netns $CNI_CONTAINERID
	echo Running: ip netns exec $CNI_CONTAINERID ip link set c-${host_if_name} up
	ip netns exec $CNI_CONTAINERID ip link set c-${host_if_name} up
	echo Running: ip netns exec $CNI_CONTAINERID ip addr add $container_ip/$subnet_mask_size dev c-${host_if_name}
	ip netns exec $CNI_CONTAINERID ip addr add $container_ip/$subnet_mask_size dev c-${host_if_name}
	echo Running: ip netns exec $CNI_CONTAINERID ip route add default via $gw_ip dev c-${host_if_name}
	ip netns exec $CNI_CONTAINERID ip route add default via $gw_ip dev c-${host_if_name}

	mac=$(ip netns exec $CNI_CONTAINERID ip link show eth0 | awk '/ether/ {print $2}')
	echo Mac: $mac
response="{
  \"cniVersion\": \"0.3.1\",
  \"interfaces\": [                                            
      {
          \"name\": \"eth0\",
          \"mac\": \"$mac\",                            
          \"sandbox\": \"$CNI_NETNS\" 
      }
  ],
  \"ips\": [
      {
          \"version\": \"4\",
          \"address\": \"$container_ip/$subnet_mask_size\",
          \"gateway\": \"$gw_ip\",          
          \"interface\": 0 
      }
  ]
}"
        echo $reponse
        echo $reponse >&3
;;

DEL)
	ip=$(ip netns exec $CNI_CONTAINERID ip addr show eth0 | awk '/inet / {print $2}' | sed  s%/.*%% || echo "")
	if [ ! -z "$ip" ]
	then
		sed -i "/$ip/d" $IP_STORE
	fi
;;

GET)
	echo "GET not supported"
	exit 1
;;

VERSION)
echo '{
  "cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ] 
}' >&3
;;

*)
  echo "Unknown cni commandn: $CNI_COMMAND" 
  exit 1
;;

esac
